### ISSUE TITLE
.

### ISSUE THREAD

**Issue by rancidfrog** [sonyxperiadev/camera#47]
.

**Comment by rancidfrog** [comment]
```
01-01 22:17:10.319   438  4238 D FocuspeakProcessorApi2: kill()
01-01 22:17:10.319   438  4238 D Camera2Fragment: Start Preview
01-01 22:17:10.319   438  4238 D PictureModuleApi2: Start Preview
01-01 22:17:10.320   438  4238 D PictureModuleApi2: ImageReader RAW_SENOSR
01-01 22:17:10.320   438  4238 D AndroidRuntime: Shutting down VM
01-01 22:17:10.321   438  4238 E AndroidRuntime: FATAL EXCEPTION: main
01-01 22:17:10.321   438  4238 E AndroidRuntime: Process: troop.com.freedcam, PID: 4238
01-01 22:17:10.321   438  4238 E AndroidRuntime: java.util.NoSuchElementException
01-01 22:17:10.321   438  4238 E AndroidRuntime: 	at java.util.AbstractList$Itr.next(AbstractList.java:364)
01-01 22:17:10.321   438  4238 E AndroidRuntime: 	at java.util.Collections.max(Collections.java:781)
01-01 22:17:10.321   438  4238 E AndroidRuntime: 	at freed.cam.apis.camera2.modules.PictureModuleApi2.startPreview(PictureModuleApi2.java:868)
01-01 22:17:10.321   438  4238 E AndroidRuntime: 	at freed.cam.apis.camera2.Camera2Fragment.StartPreview(Camera2Fragment.java:121)
01-01 22:17:10.321   438  4238 E AndroidRuntime: 	at freed.cam.apis.camera2.parameters.manual.BurstApi2$1.run(BurstApi2.java:105)
01-01 22:17:10.321   438  4238 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
01-01 22:17:10.321   438  4238 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-01 22:17:10.321   438  4238 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
01-01 22:17:10.321   438  4238 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
01-01 22:17:10.321   438  4238 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-01 22:17:10.321   438  4238 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
01-01 22:17:10.321   438  4238 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
01-01 22:17:10.322   438  2847 I am_crash: [4238,0,troop.com.freedcam,949534278,java.util.NoSuchElementException,NULL,AbstractList.java,364]
```

**Comment by rancidfrog** [comment]
@jerpelea 
Any updates on focus issues? [Z3 series seem to be worse with new blobs]
older blobs used to focus after a while, now the new blobs focus then unfocus right before taking picture resulting in blurry photo.
Freedcam all settings same result.
Opencamera has best settings result in regards to +- brightness, still too dark in most cases, only opencamera seems to change better

**Comment by rancidfrog** [comment]
@jerpelea
Latest binaries v10 still have AF and brightness issues.
Also, with aosp camera and FreeDCam front camera is upside down.

**Comment by rancidfrog** [comment]
@jerpelea 
Regarding SW_binaries_for_Xperia_AOSP_M_MR1_3.10_v11_legacy blobs,
AF issues persist, brightness does not apply well, very dark most of the times
Front camera preview is upside down - however it saves correct orientation, 
Also, front camera has better focus and brightness than back camera, **but it is very grainy**.

Aries 7.1.2 n-mr1 branch
